/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

type Language = 'en' | 'pl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    'nav.problem': 'Problem',
    'nav.howItWorks': 'How it works',
    'nav.useCases': 'Use cases',
    'nav.faq': 'FAQ',
    'nav.whitepaper': 'Whitepaper',
    'nav.demo': 'Demo',
    'nav.login': 'Login',
    'nav.getStarted': 'Get started',

    // Hero
    'hero.badge': 'Early Access',
    'hero.title1': 'Immutable history',
    'hero.title2': 'of your products',
    'hero.subtitle': 'TRVE is an immutable registry for every valuable product, recorded on blockchain forever. Document purchases, services, repairs — once recorded, never lost.',
    'hero.cta': 'Register for free',
    'hero.ctaSecondary': 'See how it works →',

    // Problem & Solution
    'problemSolution.title': 'Problem & Solution',
    'problem.label': 'Problem',
    'problem.title': 'Products lose their history over time',
    'problem.subtitle': 'Product data disappears, documents get lost, and history cannot be verified.',
    'problem.item1.title': 'Lower value',
    'problem.item1.desc': 'Unverified products lose market value.',
    'problem.item2.title': 'Time wasted',
    'problem.item2.desc': 'You waste time proving what happened.',
    'problem.item3.title': 'No trust',
    'problem.item3.desc': 'There is no reliable product record.',
    'solution.label': 'Solution',
    'solution.title': 'TRVE: immutable product history',
    'solution.subtitle': 'Every product has a unique ID. Events are recorded on blockchain — they cannot be changed.',
    'solution.item1.title': 'Blockchain',
    'solution.item1.desc': 'Events are recorded on blockchain.',
    'solution.item2.title': 'Immutability',
    'solution.item2.desc': 'No one can change or delete the data.',
    'solution.item3.title': 'Verification',
    'solution.item3.desc': 'Anyone can verify full history.',

    // How it works
    'howItWorks.title': 'How it works',
    'howItWorks.subtitle': 'Three simple steps to immutable history',
    'howItWorks.step1.title': 'Create product identity',
    'howItWorks.step1.desc': 'Register product details, photos and proof of origin.',
    'howItWorks.step2.title': 'Build product history',
    'howItWorks.step2.desc': 'Add services, inspections, repairs and updates over time.',
    'howItWorks.step3.title': 'Verify or transfer ownership',
    'howItWorks.step3.desc': 'Anyone can verify history. Ownership can be transferred to next owner.',

    // Use cases
    'useCases.title': 'Use cases',
    'useCases.subtitle': 'What products can have a TRVE history',
    'useCases.vehicles': 'Vehicles',
    'useCases.vehicles.desc': 'Service history, inspections, repairs.',
    'useCases.watches': 'Watches',
    'useCases.watches.desc': 'Proof of purchase, services, authenticity.',
    'useCases.art': 'Art',
    'useCases.art.desc': 'Provenance, exhibitions, ownership.',
    'useCases.instruments': 'Instruments',
    'useCases.instruments.desc': 'Setup, services, usage history.',
    'useCases.anything': 'Anything',
    'useCases.anything.desc': 'Any product with value.',
    'useCases.evolving': 'Constantly evolving',
    'useCases.evolvingDesc': 'New features and possibilities are added as the platform grows. This is just the beginning.',

    // For Manufacturers
    'manufacturers.title': 'For manufacturers',
    'manufacturers.desc': 'Manufacturers can create product identity at production stage and attach verified origin data from day one.',
    'manufacturers.item1.title': 'Product identity',
    'manufacturers.item1.desc': 'Each product gets unique blockchain identity at factory.',
    'manufacturers.item2.title': 'Proof of origin',
    'manufacturers.item2.desc': 'Verified manufacturing data and certificates.',
    'manufacturers.item3.title': 'Anti-counterfeiting',
    'manufacturers.item3.desc': 'Customers can verify if product is original.',
    'manufacturers.item4.title': 'Lifecycle tracking',
    'manufacturers.item4.desc': 'Full visibility across servicing and resale.',
    'manufacturers.item5.title': 'Brand protection',
    'manufacturers.item5.desc': 'Stolen or fake products damage brand reputation.',
    'manufacturers.summary': 'TRVE becomes a shared product record between manufacturer, owner and service partners.',

    // Security - Stolen Flag
    'security.title': 'Product status',
    'security.flag.title': 'Product ownership and theft status',
    'security.flag.desc': 'Owner can report a product as stolen. The status becomes part of the product history and is visible during every verification.',
    'security.benefit1': 'Protects buyers and manufacturers',
    'security.benefit2': 'Limits illegal resale',
    'security.benefit3': 'Increases trust in product history',
    'security.note': 'Applies to all products registered in TRVE.',
    'security.warning': 'ITEM REPORTED STOLEN',
    'security.warningDesc': 'This product has been reported as stolen by its owner. The status is permanently recorded on blockchain.',

    // Roadmap
    'roadmap.title': 'Roadmap',
    'roadmap.subtitle': 'Where we\'re heading',
    'roadmap.phase1': 'Blockchain Anchoring',
    'roadmap.phase1.item1': 'Product registration',
    'roadmap.phase1.item2': 'Merkle proof verification',
    'roadmap.phase1.item3': 'Blockchain record anchoring',
    'roadmap.phase1.item4': 'Public verification',
    'roadmap.phase1.item5': 'Basic ownership management',
    'roadmap.phase2': 'Data & Integrations',
    'roadmap.phase2.item1': 'Manufacturer integrations',
    'roadmap.phase2.item2': 'Service center partnerships',
    'roadmap.phase2.item3': 'Certificates on-chain',
    'roadmap.phase2.item4': 'Ownership transfer protocol',
    'roadmap.phase2.item5': 'NFT-ready data structure',
    'roadmap.phase3': 'Decentralized Storage',
    'roadmap.phase3.item1': 'Stolen goods registry',
    'roadmap.phase3.item2': 'Insurance integration',
    'roadmap.phase3.item3': 'Public APIs',
    'roadmap.phase3.item4': 'IPFS integration',
    'roadmap.phase3.item5': 'Decentralized asset storage',
    'roadmap.phase4': 'NFT & Ownership',
    'roadmap.phase4.item1': 'Mobile apps',
    'roadmap.phase4.item2': 'AI verification',
    'roadmap.phase4.item3': 'NFT for each asset',
    'roadmap.phase4.item4': 'On-chain ownership transfers',
    'roadmap.phase4.item5': 'Wallet integration (optional)',

    // FAQ
    'faq.title': 'FAQ',
    'faq.subtitle': 'Frequently asked questions',
    'faq.q1': 'Is it really free?',
    'faq.a1': 'MVP — yes, completely free. Test it and give feedback.',
    'faq.q2': 'Do I need to understand blockchain?',
    'faq.a2': 'No. TRVE works like a normal app. Blockchain runs under the hood.',
    'faq.q3': 'Can I register anything?',
    'faq.a3': 'Yes. Any product that has value.',
    'faq.q4': 'Can I edit the history?',
    'faq.a4': 'No. Once recorded, it cannot be changed.',

    // CTA
    'cta.badge': 'Get started now',
    'cta.title': 'Build immutable history of your products',
    'cta.subtitle': 'Free. No commitments. First 1000 items — free forever.',
    'cta.primary': 'Register your first product',
    'cta.secondary': 'See demo →',

    // Contact
    'contact.sectionTitle': 'Contact',
    'contact.headline': 'Let\'s build the future of product identity together',
    'contact.questions': 'Got questions?',
    'contact.writeUs': 'Write to me',
    'contact.email': 'Email',
    'contact.response': 'I typically respond within 24 hours.',
    'contact.emailAddress': 'hello@trve.io',
    'contact.status': 'Online and ready to help',

    // Newsletter
    'newsletter.title': 'Newsletter',
    'newsletter.stayUpdated': 'Stay in the loop',
    'newsletter.news': 'TRVE updates',
    'newsletter.newsDesc': 'Product updates, new features, and insights delivered to your inbox.',
    'newsletter.placeholder': 'Enter your email',
    'newsletter.submit': 'Subscribe',
    'newsletter.submitting': 'Subscribing...',
    'newsletter.success': 'You\'re in! Thank you for subscribing.',
    'newsletter.error': 'An error occurred. Please try again.',
    'newsletter.privacy': 'No spam. Unsubscribe anytime.',
    'newsletter.feature1': 'Monthly updates',
    'newsletter.feature2': 'Early access',

    // Footer
    'footer.tagline': 'Immutable registry for valuable products. Every item has a story — we make sure it\'s never lost.',
    'footer.product': 'Product',
    'footer.resources': 'Resources',
    'footer.contact': 'Connect',
    'footer.copyright': '© 2026 TRVE.io',
    'footer.slogan': 'Built on blockchain. Built for trust.',
    'footer.version': 'Early Access v0.1',
    'footer.tech': 'Blockchain-powered',
    'footer.docs': 'Documentation',
    'footer.api': 'API (coming soon)',
    'footer.status': 'System status',
    'footer.contactForm': 'Contact form',
    'footer.backToTop': 'Back to top',

    // Stats
    'stats.immutable': 'Immutable',
    'stats.transparent': 'Transparent',
    'stats.accessible': 'Accessible',

    // How It Works Page (guide)
    'howItWorks.heroTitle': 'How TRVE Works',
    'howItWorks.heroSubtitle': 'A simple guide to creating immutable product history on the blockchain',
    'howItWorks.whatIsAssetTitle': 'What is an Asset in TRVE?',
    'howItWorks.whatIsAssetDesc': 'An asset is any valuable item you want to document — a car, watch, artwork, instrument, or anything else with history worth preserving. TRVE creates a unique digital identity for each asset, stored permanently on the blockchain.',
    'howItWorks.stepsTitle': 'Four Simple Steps',
    'howItWorks.step1Title': 'Create an Account',
    'howItWorks.step1Desc': 'Sign up for free. No blockchain knowledge required — we handle the technical details.',
    'howItWorks.step2Title': 'Register Your Asset',
    'howItWorks.step2Desc': 'Add product details: name, brand, serial number, purchase info, and attach documents like receipts or certificates.',
    'howItWorks.step3Title': 'Verify Information',
    'howItWorks.step3Desc': 'Review your data. Once verified, the asset is prepared for blockchain anchoring — creating a permanent, tamper-proof record.',
    'howItWorks.step4Title': 'Mint to Blockchain',
    'howItWorks.step4Desc': 'The final step creates an immutable record. Anyone can verify the complete history of your asset forever.',
    'howItWorks.statusTitle': 'Understanding Asset Status',
    'howItWorks.statusDraftDesc': 'Asset is being created. You can still edit all information freely.',
    'howItWorks.statusVerifiedDesc': 'Information is complete and verified. Ready for blockchain minting.',
    'howItWorks.statusMintedDesc': 'Permanently recorded on blockchain. History is now immutable.',
    'howItWorks.benefitsTitle': 'Why Register on Blockchain?',
    'howItWorks.benefit1Title': 'Permanent Record',
    'howItWorks.benefit1Desc': 'Data cannot be lost, altered, or deleted. Your asset history exists forever.',
    'howItWorks.benefit2Title': 'Instant Verification',
    'howItWorks.benefit2Desc': 'Anyone can verify authenticity and history in seconds, increasing trust and value.',
    'howItWorks.benefit3Title': 'Higher Resale Value',
    'howItWorks.benefit3Desc': 'Products with verified history command premium prices in secondary markets.',
    'howItWorks.benefit4Title': 'Proof of Ownership',
    'howItWorks.benefit4Desc': 'Cryptographic proof that you own what you claim to own. Useful for insurance and disputes.',
    'howItWorks.ctaTitle': 'Ready to Start?',
    'howItWorks.ctaDesc': 'Create your first asset in minutes. Free during Early Access.',
    'howItWorks.ctaButton': 'Register First Asset',
    'howItWorks.readWhitepaper': 'Read Whitepaper',
    'common.goToApp': 'Go to App',
    'common.phase2': 'Phase 2',
    'footer.allRightsReserved': 'All rights reserved.',

    // Tooltips
    'tooltip.assetName': 'Give your asset a recognizable name. This will be the main identifier.',
    'tooltip.assetType': 'Category helps organize assets and enables type-specific features.',
    'tooltip.serialNumber': 'Unique manufacturer identifier. Helps verify authenticity.',
    'tooltip.brand': 'The manufacturer or brand name of the product.',
    'tooltip.model': 'Specific model designation from the manufacturer.',
    'tooltip.description': 'Additional details about condition, history, or special features.',
    'tooltip.documents': 'Attach receipts, certificates, photos. Documents are hashed for verification.',
    'tooltip.statusDraft': 'Draft: Still being edited. Not yet on blockchain.',
    'tooltip.statusVerified': 'Verified: Data complete and reviewed. Ready to mint.',
    'tooltip.statusMinted': 'Minted: Permanently recorded on blockchain. Cannot be changed.',
    'tooltip.totalAssets': 'Total number of assets you have registered in TRVE.',
    'tooltip.draftCount': 'Assets still being created or edited.',
    'tooltip.verifiedCount': 'Assets verified and ready for blockchain minting.',
    'tooltip.mintedCount': 'Assets permanently recorded on blockchain.',

    // Admin Panel
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.organizations': 'Organizations',
    'admin.assets': 'Assets',
    'admin.newsletter': 'Newsletter',
    'admin.security': 'Security',
    'admin.backToApp': 'Back to App',
    'admin.adminPanel': 'Admin Panel',
    'admin.loading': 'Loading...',
    'admin.retry': 'Retry',
    'admin.dismiss': 'Dismiss',
    'admin.user': 'User',
    'admin.actions': 'Actions',
    'admin.createdAt': 'Created',
    'admin.unlocking': 'Unlocking...',
    'admin.confirming': 'Confirming...',

    // Admin Dashboard
    'admin.dashboard.title': 'Admin Dashboard',
    'admin.dashboard.subtitle': 'System overview and statistics',
    'admin.dashboard.totalUsers': 'Total Users',
    'admin.dashboard.organizations': 'Organizations',
    'admin.dashboard.totalAssets': 'Total Assets',
    'admin.dashboard.verifiedAssets': 'Verified Assets',
    'admin.dashboard.active': 'active',
    'admin.dashboard.verified': 'verified',
    'admin.dashboard.minted': 'minted',
    'admin.dashboard.readyForMinting': 'Ready for minting',

    // Admin Security
    'admin.security.title': 'Security',
    'admin.security.subtitle': 'Manage locked accounts and user security',
    'admin.security.lockedUsers': 'Locked Users',
    'admin.security.failedAttempts': 'Failed Attempts',
    'admin.security.unconfirmedEmails': 'Unconfirmed Emails',
    'admin.security.totalUsers': 'Total Users',
    'admin.security.lockedUsersTitle': 'Locked Users',
    'admin.security.noLockedUsers': 'No locked users',
    'admin.security.failedCount': 'Failed Count',
    'admin.security.lockoutEnd': 'Lockout Ends',
    'admin.security.attempts': 'attempts',
    'admin.security.unlock': 'Unlock',
    'admin.security.unconfirmedEmailsTitle': 'Unconfirmed Emails',
    'admin.security.allEmailsConfirmed': 'All emails confirmed',
    'admin.security.confirmEmail': 'Confirm Email',
    'admin.security.andMore': 'And {count} more...',

    // Admin Dashboard extras
    'admin.dashboard.userStats': 'User Statistics',
    'admin.dashboard.viewAll': 'View all',
    'admin.dashboard.activeUsers': 'Active Users',
    'admin.dashboard.inactive': 'Inactive',
    'admin.dashboard.activePercent': 'active',
    'admin.dashboard.assetPipeline': 'Asset Pipeline',
    'admin.dashboard.draft': 'Draft',
    'admin.dashboard.manageUsers': 'Manage Users',
    'admin.dashboard.viewEditUsers': 'View and edit users',
    'admin.dashboard.verifyOrganizations': 'Verify organizations',
    'admin.dashboard.allAssets': 'All Assets',
    'admin.dashboard.browseAssets': 'Browse all assets',
    'admin.dashboard.viewSubscribers': 'View subscribers',

    // Admin Users
    'admin.users.title': 'Users',
    'admin.users.subtitle': 'Manage all users in the system',
    'admin.users.search': 'Search users...',
    'admin.users.allRoles': 'All roles',
    'admin.users.allStatuses': 'All statuses',
    'admin.users.active': 'Active',
    'admin.users.inactive': 'Inactive',
    'admin.users.noUsers': 'No users found',
    'admin.users.role': 'Role',
    'admin.users.status': 'Status',
    'admin.users.email': 'Email',
    'admin.users.organization': 'Organization',
    'admin.users.view': 'View',
    'admin.users.previous': 'Previous',
    'admin.users.next': 'Next',
    'admin.users.page': 'Page',
    'admin.users.of': 'of',

    // Admin User Detail
    'admin.userDetail.title': 'User Details',
    'admin.userDetail.back': 'Back to users',
    'admin.userDetail.userInfo': 'User Information',
    'admin.userDetail.username': 'Username',
    'admin.userDetail.email': 'Email',
    'admin.userDetail.role': 'Role',
    'admin.userDetail.organization': 'Organization',
    'admin.userDetail.createdAt': 'Created At',
    'admin.userDetail.status': 'Status',
    'admin.userDetail.emailStatus': 'Email Status',
    'admin.userDetail.confirmed': 'Confirmed',
    'admin.userDetail.notConfirmed': 'Not Confirmed',
    'admin.userDetail.actions': 'Actions',
    'admin.userDetail.activate': 'Activate User',
    'admin.userDetail.deactivate': 'Deactivate User',
    'admin.userDetail.confirmEmail': 'Confirm Email',
    'admin.userDetail.userAssets': 'User Assets',
    'admin.userDetail.noAssets': 'No assets found for this user',
    'admin.userDetail.notFound': 'User not found',

    // Admin Organizations
    'admin.orgs.title': 'Organizations',
    'admin.orgs.subtitle': 'Manage all organizations',
    'admin.orgs.search': 'Search organizations...',
    'admin.orgs.allStatuses': 'All statuses',
    'admin.orgs.verified': 'Verified',
    'admin.orgs.unverified': 'Unverified',
    'admin.orgs.noOrgs': 'No organizations found',
    'admin.orgs.members': 'Members',
    'admin.orgs.assets': 'Assets',
    'admin.orgs.view': 'View',
    'admin.orgs.verify': 'Verify',
    'admin.orgs.unverify': 'Unverify',

    // Admin Organization Detail
    'admin.orgDetail.title': 'Organization Details',
    'admin.orgDetail.back': 'Back to organizations',
    'admin.orgDetail.info': 'Organization Information',
    'admin.orgDetail.name': 'Name',
    'admin.orgDetail.description': 'Description',
    'admin.orgDetail.walletAddress': 'Wallet Address',
    'admin.orgDetail.verified': 'Verified',
    'admin.orgDetail.createdAt': 'Created At',
    'admin.orgDetail.yes': 'Yes',
    'admin.orgDetail.no': 'No',
    'admin.orgDetail.actions': 'Actions',
    'admin.orgDetail.verify': 'Verify Organization',
    'admin.orgDetail.unverify': 'Remove Verification',
    'admin.orgDetail.members': 'Members',
    'admin.orgDetail.noMembers': 'No members found',
    'admin.orgDetail.notFound': 'Organization not found',

    // Admin Assets
    'admin.assets.title': 'Assets',
    'admin.assets.subtitle': 'Browse all assets in the system',
    'admin.assets.search': 'Search assets...',
    'admin.assets.allCategories': 'All categories',
    'admin.assets.allStatuses': 'All statuses',
    'admin.assets.minted': 'Minted',
    'admin.assets.notMinted': 'Not minted',
    'admin.assets.noAssets': 'No assets found',
    'admin.assets.owner': 'Owner',
    'admin.assets.category': 'Category',
    'admin.assets.view': 'View',

    // Admin Newsletter
    'admin.newsletter.title': 'Newsletter Subscribers',
    'admin.newsletter.subtitle': 'Manage newsletter subscriptions',
    'admin.newsletter.search': 'Search by email...',
    'admin.newsletter.noSubscribers': 'No subscribers found',
    'admin.newsletter.subscribedAt': 'Subscribed At',
    'admin.newsletter.totalSubscribers': 'Total Subscribers',

    // App Layout
    'app.dashboard': 'Dashboard',
    'app.assets': 'Assets',
    'app.reports': 'Reports',
    'app.newAsset': 'New Asset',
    'app.adminPanel': 'Admin Panel',
    'app.signOut': 'Sign out',
    'app.editAsset': 'Edit Asset',
    'app.settings': 'Settings',
    'settings.title': 'Settings',
    'settings.appearance': 'Appearance',
    'settings.theme': 'Theme',
    'settings.themeLight': 'Light',
    'settings.themeDark': 'Dark',
    'settings.language': 'Language',
    'settings.languageEn': 'English',
    'settings.languagePl': 'Polski',

    // Documents
    'documents.title': 'Documents',
    'documents.upload': 'Upload Document',
    'documents.empty': 'No documents attached',
    'documents.saveFirst': 'Save the asset first to attach documents',
    'documents.blockchainNote': 'Documents are included in blockchain verification',
    'documents.delete': 'Delete',
    'documents.download': 'Download',
    'documents.view': 'View',
    'documents.uploading': 'Uploading...',
    'documents.hash': 'Hash',
    'documents.size': 'Size',

    // Common
    'common.loading': 'Loading...',
    'common.saving': 'Saving...',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirmDelete': 'Are you sure you want to delete this asset?',

    // Asset Form
    'asset.new': 'New Asset',
    'asset.edit': 'Edit Asset',
    'asset.newSubtitle': 'Register a new product in the registry',
    'asset.editSubtitle': 'Update asset information',
    'asset.type': 'Asset Type',
    'asset.typeSubtitle': 'Select the category of your product',
    'asset.basicInfo': 'Basic Information',
    'asset.basicInfoSubtitle': 'Primary details about the product',
    'asset.name': 'Name',
    'asset.namePlaceholder': 'e.g. Rolex Submariner',
    'asset.brand': 'Brand',
    'asset.brandPlaceholder': 'e.g. Rolex',
    'asset.model': 'Model',
    'asset.modelPlaceholder': 'e.g. Submariner Date',
    'asset.serialNumber': 'Serial Number',
    'asset.serialNumberPlaceholder': 'e.g. SN-12345678',
    'asset.uniqueId': 'Unique ID',
    'asset.purchaseDetails': 'Purchase Details',
    'asset.purchaseDetailsSubtitle': 'Origin and acquisition information',
    'asset.exactProductionDate': 'Exact production date',
    'asset.productionDate': 'Production Date',
    'asset.year': 'Year',
    'asset.yearPlaceholder': 'e.g. 2023',
    'asset.purchaseDate': 'Purchase Date',
    'asset.purchasePrice': 'Purchase Price',
    'asset.currency': 'Currency',
    'asset.description': 'Description',
    'asset.descriptionPlaceholder': 'Additional information about the product...',
    'asset.descriptionHint': 'Include condition, provenance, or any relevant details',
    'asset.blockchainRecord': 'Blockchain Record',
    'asset.blockchainRecordDesc': 'Once saved, this information will be prepared for blockchain verification. The record becomes immutable after minting.',
    'asset.saveChanges': 'Save Changes',
    'asset.createAsset': 'Create Asset',

    // Asset Types / Categories
    'category.vehicle': 'Vehicle',
    'category.watch': 'Watch',
    'category.electronics': 'Electronics',
    'category.art': 'Art',
    'category.instrument': 'Instrument',
    'category.other': 'Other',

    // Assets List
    'assets.title': 'Assets',
    'assets.subtitle': 'Manage your registered products',
    'assets.addAsset': 'Add Asset',
    'assets.searchPlaceholder': 'Search by name, serial number...',
    'assets.allTypes': 'All Types',
    'assets.allStatus': 'All Status',
    'assets.tableProduct': 'Product',
    'assets.tableType': 'Type',
    'assets.tableStatus': 'Status',
    'assets.tableSerial': 'Serial',
    'assets.tableActions': 'Actions',
    'assets.noAssetsYet': 'No assets registered yet',
    'assets.noAssetsMatch': 'No assets match your filters',
    'assets.addFirstAsset': 'Add your first asset →',
    'assets.showing': 'Showing',
    'assets.of': 'of',
    'assets.assets': 'assets',

    // Status Labels
    'status.draft': 'Draft',
    'status.verified': 'Verified',
    'status.minted': 'Minted',

    // Asset Types
    'assetType.VEHICLE': 'Vehicle',
    'assetType.WATCH': 'Watch',
    'assetType.ELECTRONICS': 'Electronics',
    'assetType.ART': 'Art',
    'assetType.INSTRUMENT': 'Instrument',
    'assetType.OTHER': 'Other',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of your product registry',
    'dashboard.totalAssets': 'Total Assets',
    'dashboard.allRegisteredItems': 'All registered items',
    'dashboard.draft': 'Draft',
    'dashboard.awaitingCompletion': 'Awaiting completion',
    'dashboard.verified': 'Verified',
    'dashboard.readyToMint': 'Ready to mint',
    'dashboard.minted': 'Minted',
    'dashboard.onBlockchain': 'On blockchain',
    'dashboard.assetsByType': 'Assets by Type',
    'dashboard.types': 'types',
    'dashboard.noAssetsYet': 'No assets yet',
    'dashboard.addFirstAsset': 'Add your first asset →',
    'dashboard.recentAssets': 'Recent Assets',
    'dashboard.viewAll': 'View all →',
    'dashboard.noRecentActivity': 'No recent activity',
    'dashboard.assetPipeline': 'Asset Pipeline',

    // Reports
    'reports.title': 'Reports',
    'reports.subtitle': 'Analytics and asset summaries',
    'reports.comingSoon': 'Coming Soon',
    'reports.moduleInDevelopment': 'Reports module in development',
    'reports.moduleDescription': 'We\'re working on advanced reports and visualizations. You\'ll be able to generate asset value summaries, maintenance costs, depreciation analysis and more.',
    'reports.plannedFeatures': 'Planned Features',
    'reports.plannedFeaturesSubtitle': 'What\'s coming to the reports module',
    'reports.featuresPlanned': 'features planned',
    'reports.feature': 'Feature',
    'reports.planned': 'Planned',
    'reports.haveSuggestions': 'Have suggestions?',
    'reports.feedbackDescription': 'We\'re building this for you. Let us know what reports and analytics would be most valuable for your use case.',
    'reports.sendFeedback': 'Send feedback',
    'reports.valueReport': 'Value Report',
    'reports.valueReportDesc': 'Total asset value breakdown by category',
    'reports.depreciation': 'Depreciation',
    'reports.depreciationDesc': 'Asset value loss analysis over time',
    'reports.serviceCosts': 'Service Costs',
    'reports.serviceCostsDesc': 'Maintenance and repair cost breakdown',
    'reports.assignments': 'Assignments',
    'reports.assignmentsDesc': 'Assets assigned to team members',
    'reports.dataExport': 'Data Export',
    'reports.dataExportDesc': 'Export to PDF, Excel and CSV formats',
    'reports.serviceSchedule': 'Service Schedule',
    'reports.serviceScheduleDesc': 'Calendar of planned inspections and services',
  },
  pl: {
    // Nav
    'nav.problem': 'Problem',
    'nav.howItWorks': 'Jak działa',
    'nav.useCases': 'Zastosowania',
    'nav.faq': 'FAQ',
    'nav.whitepaper': 'Whitepaper',
    'nav.demo': 'Demo',
    'nav.login': 'Zaloguj',
    'nav.getStarted': 'Rozpocznij',

    // Hero
    'hero.badge': 'Early Access',
    'hero.title1': 'Niezmienna historia',
    'hero.title2': 'Twoich produktów',
    'hero.subtitle': 'TRVE to niezmienny rejestr każdego wartościowego produktu, zapisany w blockchain na zawsze. Dokumentuj zakupy, serwisy, naprawy — raz zapisane, nigdy nie znikną.',
    'hero.cta': 'Zarejestruj za darmo',
    'hero.ctaSecondary': 'Zobacz jak działa →',

    // Problem & Solution
    'problemSolution.title': 'Problem i Rozwiązanie',
    'problem.label': 'Problem',
    'problem.title': 'Produkty tracą swoją historię w czasie',
    'problem.subtitle': 'Informacje o produkcie znikają, dokumenty giną, a historia nie jest weryfikowalna.',
    'problem.item1.title': 'Niższa wartość',
    'problem.item1.desc': 'Produkty bez historii są wyceniane niżej.',
    'problem.item2.title': 'Strata czasu',
    'problem.item2.desc': 'Tracisz czas na udowadnianie faktów.',
    'problem.item3.title': 'Brak zaufania',
    'problem.item3.desc': 'Brak wiarygodnej historii produktu.',
    'solution.label': 'Rozwiązanie',
    'solution.title': 'TRVE: niezmienna historia produktu',
    'solution.subtitle': 'Każdy produkt ma unikalny identyfikator. Zdarzenia są zapisywane w blockchain — nie da się ich zmienić.',
    'solution.item1.title': 'Blockchain',
    'solution.item1.desc': 'Zdarzenia zapisywane są w blockchain.',
    'solution.item2.title': 'Niezmienność',
    'solution.item2.desc': 'Nikt nie może zmienić ani usunąć danych.',
    'solution.item3.title': 'Weryfikacja',
    'solution.item3.desc': 'Każdy może zweryfikować historię produktu.',

    // How it works
    'howItWorks.title': 'Jak to działa',
    'howItWorks.subtitle': 'Trzy proste kroki do niezmiennej historii',
    'howItWorks.step1.title': 'Utwórz tożsamość produktu',
    'howItWorks.step1.desc': 'Zarejestruj dane produktu, zdjęcia i dowód pochodzenia.',
    'howItWorks.step2.title': 'Buduj historię produktu',
    'howItWorks.step2.desc': 'Dodawaj serwisy, przeglądy, naprawy i aktualizacje w czasie.',
    'howItWorks.step3.title': 'Zweryfikuj lub przekaż własność',
    'howItWorks.step3.desc': 'Każdy może sprawdzić historię. Własność można przekazać kolejnemu właścicielowi.',

    // Use cases
    'useCases.title': 'Zastosowania',
    'useCases.subtitle': 'Jakie produkty mogą mieć historię w TRVE',
    'useCases.vehicles': 'Samochody',
    'useCases.vehicles.desc': 'Historia serwisowa, przeglądy, naprawy.',
    'useCases.watches': 'Zegarki',
    'useCases.watches.desc': 'Dowód zakupu, serwisy, autentyczność.',
    'useCases.art': 'Sztuka',
    'useCases.art.desc': 'Proweniencja, wystawy, właściciele.',
    'useCases.instruments': 'Instrumenty',
    'useCases.instruments.desc': 'Setup, serwisy, historia użycia.',
    'useCases.anything': 'Cokolwiek',
    'useCases.anything.desc': 'Każdy produkt, który ma wartość.',
    'useCases.evolving': 'Ciągle się rozwijamy',
    'useCases.evolvingDesc': 'Nowe funkcje i możliwości pojawiają się wraz z rozwojem platformy. To dopiero początek.',

    // For Manufacturers
    'manufacturers.title': 'Dla producentów',
    'manufacturers.desc': 'Producenci mogą tworzyć tożsamość produktu już na etapie produkcji i dodawać zweryfikowane dane od pierwszego dnia.',
    'manufacturers.item1.title': 'Tożsamość produktu',
    'manufacturers.item1.desc': 'Każdy produkt dostaje unikalną tożsamość już w fabryce.',
    'manufacturers.item2.title': 'Dowód pochodzenia',
    'manufacturers.item2.desc': 'Zweryfikowane dane produkcyjne i certyfikaty.',
    'manufacturers.item3.title': 'Ochrona przed podróbkami',
    'manufacturers.item3.desc': 'Klient może sprawdzić, czy produkt jest oryginalny.',
    'manufacturers.item4.title': 'Historia w całym cyklu życia',
    'manufacturers.item4.desc': 'Pełna widoczność przez serwisy i kolejne sprzedaże.',
    'manufacturers.item5.title': 'Ochrona marki',
    'manufacturers.item5.desc': 'Kradzione i fałszywe produkty nie psują reputacji marki.',
    'manufacturers.summary': 'TRVE staje się wspólnym rejestrem produktu dla producenta, właściciela i serwisów.',

    // Security - Stolen Flag
    'security.title': 'Status produktu',
    'security.flag.title': 'Status własności i kradzieży produktu',
    'security.flag.desc': 'Właściciel może zgłosić produkt jako skradziony. Status staje się częścią historii produktu i jest widoczny przy każdej weryfikacji.',
    'security.benefit1': 'Ochrona kupujących i producentów',
    'security.benefit2': 'Ograniczenie nielegalnego obrotu',
    'security.benefit3': 'Większe zaufanie do historii produktu',
    'security.note': 'Dotyczy wszystkich produktów zarejestrowanych w TRVE.',
    'security.warning': 'PRZEDMIOT ZGŁOSZONY JAKO SKRADZIONY',
    'security.warningDesc': 'Ten produkt został zgłoszony jako skradziony przez właściciela. Status jest trwale zapisany w blockchain.',

    // Roadmap
    'roadmap.title': 'Roadmapa',
    'roadmap.subtitle': 'Gdzie zmierzamy',
    'roadmap.phase1': 'Zakotwiczenie w blockchain',
    'roadmap.phase1.item1': 'Rejestracja produktu',
    'roadmap.phase1.item2': 'Weryfikacja Merkle proof',
    'roadmap.phase1.item3': 'Zakotwiczenie w blockchain',
    'roadmap.phase1.item4': 'Publiczna weryfikacja',
    'roadmap.phase1.item5': 'Zarządzanie własnością',
    'roadmap.phase2': 'Dane i integracje',
    'roadmap.phase2.item1': 'Integracje z producentami',
    'roadmap.phase2.item2': 'Partnerstwa z serwisami',
    'roadmap.phase2.item3': 'Certyfikaty w blockchain',
    'roadmap.phase2.item4': 'Protokół transferu własności',
    'roadmap.phase2.item5': 'Struktura danych gotowa na NFT',
    'roadmap.phase3': 'Zdecentralizowane przechowywanie',
    'roadmap.phase3.item1': 'Rejestr kradzionych produktów',
    'roadmap.phase3.item2': 'Integracje z ubezpieczycielami',
    'roadmap.phase3.item3': 'Publiczne API',
    'roadmap.phase3.item4': 'Integracja IPFS',
    'roadmap.phase3.item5': 'Zdecentralizowane przechowywanie danych',
    'roadmap.phase4': 'NFT i własność',
    'roadmap.phase4.item1': 'Aplikacje mobilne',
    'roadmap.phase4.item2': 'Weryfikacja AI',
    'roadmap.phase4.item3': 'NFT dla każdego przedmiotu',
    'roadmap.phase4.item4': 'Transfery własności on-chain',
    'roadmap.phase4.item5': 'Integracja z walletami (opcjonalna)',

    // FAQ
    'faq.title': 'FAQ',
    'faq.subtitle': 'Często zadawane pytania',
    'faq.q1': 'Czy to naprawdę darmowe?',
    'faq.a1': 'MVP — tak, całkowicie za darmo. Testuj i dawaj feedback.',
    'faq.q2': 'Czy muszę znać blockchain?',
    'faq.a2': 'Nie. TRVE działa jak zwykła aplikacja. Blockchain jest pod spodem.',
    'faq.q3': 'Czy mogę zarejestrować cokolwiek?',
    'faq.a3': 'Tak. Każdy produkt, który ma wartość.',
    'faq.q4': 'Czy mogę edytować historię?',
    'faq.a4': 'Nie. Raz zapisane, nie da się zmienić.',

    // CTA
    'cta.badge': 'Rozpocznij teraz',
    'cta.title': 'Zbuduj niezmienną historię swoich produktów',
    'cta.subtitle': 'Darmowe. Bez zobowiązań. Pierwsze 1000 produktów — free forever.',
    'cta.primary': 'Zarejestruj pierwszy produkt',
    'cta.secondary': 'Zobacz demo →',

    // Contact
    'contact.sectionTitle': 'Kontakt',
    'contact.headline': 'Zbudujmy razem przyszłość tożsamości produktów',
    'contact.questions': 'Masz pytania?',
    'contact.writeUs': 'Napisz do mnie',
    'contact.email': 'Email',
    'contact.response': 'Odpowiadam zwykle w ciągu 24 godzin.',
    'contact.emailAddress': 'hello@trve.io',
    'contact.status': 'Online i gotowy do pomocy',

    // Newsletter
    'newsletter.title': 'Newsletter',
    'newsletter.stayUpdated': 'Bądź na bieżąco',
    'newsletter.news': 'Aktualności TRVE',
    'newsletter.newsDesc': 'Aktualizacje produktu, nowe funkcje i inspiracje prosto na Twój email.',
    'newsletter.placeholder': 'Wpisz swój email',
    'newsletter.submit': 'Zapisz się',
    'newsletter.submitting': 'Zapisuję...',
    'newsletter.success': 'Jesteś na liście! Dziękujemy za zapis.',
    'newsletter.error': 'Wystąpił błąd. Spróbuj ponownie.',
    'newsletter.privacy': 'Bez spamu. Wypisz się kiedy chcesz.',
    'newsletter.feature1': 'Miesięczne aktualizacje',
    'newsletter.feature2': 'Wczesny dostęp',

    // Footer
    'footer.tagline': 'Niezmienny rejestr wartościowych produktów. Każdy przedmiot ma swoją historię — sprawiamy, że nigdy nie zostanie utracona.',
    'footer.product': 'Produkt',
    'footer.resources': 'Zasoby',
    'footer.contact': 'Kontakt',
    'footer.copyright': '© 2026 TRVE.io',
    'footer.slogan': 'Built on blockchain. Built for trust.',
    'footer.version': 'Early Access v0.1',
    'footer.tech': 'Zasilany blockchain',
    'footer.docs': 'Dokumentacja',
    'footer.api': 'API (wkrótce)',
    'footer.status': 'Status systemu',
    'footer.contactForm': 'Formularz kontaktowy',
    'footer.backToTop': 'Wróć na górę',

    // Stats
    'stats.immutable': 'Niezmienny',
    'stats.transparent': 'Przejrzysty',
    'stats.accessible': 'Dostępny',

    // How It Works Page (guide)
    'howItWorks.heroTitle': 'Jak działa TRVE',
    'howItWorks.heroSubtitle': 'Prosty przewodnik po tworzeniu niezmiennej historii produktu w blockchain',
    'howItWorks.whatIsAssetTitle': 'Czym jest asset w TRVE?',
    'howItWorks.whatIsAssetDesc': 'Asset to każdy wartościowy przedmiot, który chcesz udokumentować — samochód, zegarek, dzieło sztuki, instrument lub cokolwiek innego z historią wartą zachowania. TRVE tworzy unikalną cyfrową tożsamość dla każdego assetu, przechowywaną permanentnie w blockchain.',
    'howItWorks.stepsTitle': 'Cztery proste kroki',
    'howItWorks.step1Title': 'Załóż konto',
    'howItWorks.step1Desc': 'Zarejestruj się za darmo. Nie musisz znać blockchain — my zajmujemy się technicznymi szczegółami.',
    'howItWorks.step2Title': 'Zarejestruj przedmiot',
    'howItWorks.step2Desc': 'Dodaj szczegóły produktu: nazwę, markę, numer seryjny, informacje o zakupie i załącz dokumenty jak paragony czy certyfikaty.',
    'howItWorks.step3Title': 'Zweryfikuj informacje',
    'howItWorks.step3Desc': 'Sprawdź swoje dane. Po weryfikacji przedmiot jest przygotowany do zakotwiczenia w blockchain — tworzenia permanentnego, niezmiennego zapisu.',
    'howItWorks.step4Title': 'Zakotwicz w blockchain',
    'howItWorks.step4Desc': 'Ostatni krok tworzy niezmienny zapis. Każdy może zweryfikować pełną historię Twojego przedmiotu na zawsze.',
    'howItWorks.statusTitle': 'Zrozum statusy przedmiotów',
    'howItWorks.statusDraftDesc': 'Przedmiot jest tworzony. Możesz jeszcze swobodnie edytować wszystkie informacje.',
    'howItWorks.statusVerifiedDesc': 'Informacje są kompletne i zweryfikowane. Gotowy do zakotwiczenia w blockchain.',
    'howItWorks.statusMintedDesc': 'Permanentnie zapisany w blockchain. Historia jest teraz niezmienna.',
    'howItWorks.benefitsTitle': 'Dlaczego rejestrować w blockchain?',
    'howItWorks.benefit1Title': 'Permanentny zapis',
    'howItWorks.benefit1Desc': 'Dane nie mogą być utracone, zmienione ani usunięte. Historia Twojego przedmiotu istnieje na zawsze.',
    'howItWorks.benefit2Title': 'Natychmiastowa weryfikacja',
    'howItWorks.benefit2Desc': 'Każdy może zweryfikować autentyczność i historię w sekundy, zwiększając zaufanie i wartość.',
    'howItWorks.benefit3Title': 'Wyższa wartość odsprzedaży',
    'howItWorks.benefit3Desc': 'Produkty z zweryfikowaną historią osiągają wyższe ceny na rynku wtórnym.',
    'howItWorks.benefit4Title': 'Dowód własności',
    'howItWorks.benefit4Desc': 'Kryptograficzny dowód, że posiadasz to, co twierdzisz. Przydatne dla ubezpieczeń i sporów.',
    'howItWorks.ctaTitle': 'Gotowy do startu?',
    'howItWorks.ctaDesc': 'Stwórz pierwszy przedmiot w kilka minut. Bezpłatnie w okresie Early Access.',
    'howItWorks.ctaButton': 'Zarejestruj pierwszy przedmiot',
    'howItWorks.readWhitepaper': 'Przeczytaj Whitepaper',
    'common.goToApp': 'Przejdź do aplikacji',
    'common.phase2': 'Faza 2',
    'footer.allRightsReserved': 'Wszelkie prawa zastrzeżone.',

    // Tooltips
    'tooltip.assetName': 'Nadaj przedmiotowi rozpoznawalną nazwę. To będzie główny identyfikator.',
    'tooltip.assetType': 'Kategoria pomaga organizować przedmioty i włącza funkcje specyficzne dla typu.',
    'tooltip.serialNumber': 'Unikalny identyfikator producenta. Pomaga zweryfikować autentyczność.',
    'tooltip.brand': 'Producent lub nazwa marki produktu.',
    'tooltip.model': 'Specyficzne oznaczenie modelu od producenta.',
    'tooltip.description': 'Dodatkowe szczegóły o stanie, historii lub specjalnych cechach.',
    'tooltip.documents': 'Załącz paragony, certyfikaty, zdjęcia. Dokumenty są hashowane do weryfikacji.',
    'tooltip.statusDraft': 'Szkic: Wciąż edytowany. Jeszcze nie w blockchain.',
    'tooltip.statusVerified': 'Zweryfikowany: Dane kompletne i sprawdzone. Gotowy do zakotwiczenia.',
    'tooltip.statusMinted': 'Zakotwiczony: Permanentnie zapisany w blockchain. Nie można zmienić.',
    'tooltip.totalAssets': 'Całkowita liczba assetów zarejestrowanych w TRVE.',
    'tooltip.draftCount': 'Przedmioty wciąż tworzone lub edytowane.',
    'tooltip.verifiedCount': 'Przedmioty zweryfikowane i gotowe do zakotwiczenia w blockchain.',
    'tooltip.mintedCount': 'Przedmioty permanentnie zapisane w blockchain.',

    // Admin Panel
    'admin.dashboard': 'Panel',
    'admin.users': 'Użytkownicy',
    'admin.organizations': 'Organizacje',
    'admin.assets': 'Przedmioty',
    'admin.newsletter': 'Newsletter',
    'admin.security': 'Bezpieczeństwo',
    'admin.backToApp': 'Powrót do aplikacji',
    'admin.adminPanel': 'Panel Admina',
    'admin.loading': 'Ładowanie...',
    'admin.retry': 'Ponów',
    'admin.dismiss': 'Zamknij',
    'admin.user': 'Użytkownik',
    'admin.actions': 'Akcje',
    'admin.createdAt': 'Utworzono',
    'admin.unlocking': 'Odblokowywanie...',
    'admin.confirming': 'Potwierdzanie...',

    // Admin Dashboard
    'admin.dashboard.title': 'Panel Administracyjny',
    'admin.dashboard.subtitle': 'Przegląd systemu i statystyki',
    'admin.dashboard.totalUsers': 'Użytkownicy',
    'admin.dashboard.organizations': 'Organizacje',
    'admin.dashboard.totalAssets': 'Przedmioty',
    'admin.dashboard.verifiedAssets': 'Zweryfikowane',
    'admin.dashboard.active': 'aktywnych',
    'admin.dashboard.verified': 'zweryfikowanych',
    'admin.dashboard.minted': 'zakotwiczonych',
    'admin.dashboard.readyForMinting': 'Gotowe do bicia',

    // Admin Security
    'admin.security.title': 'Bezpieczeństwo',
    'admin.security.subtitle': 'Zarządzanie zablokowanymi kontami i bezpieczeństwem',
    'admin.security.lockedUsers': 'Zablokowani',
    'admin.security.failedAttempts': 'Nieudane próby',
    'admin.security.unconfirmedEmails': 'Niepotwierdzone emaile',
    'admin.security.totalUsers': 'Wszyscy użytkownicy',
    'admin.security.lockedUsersTitle': 'Zablokowani użytkownicy',
    'admin.security.noLockedUsers': 'Brak zablokowanych użytkowników',
    'admin.security.failedCount': 'Nieudane próby',
    'admin.security.lockoutEnd': 'Koniec blokady',
    'admin.security.attempts': 'prób',
    'admin.security.unlock': 'Odblokuj',
    'admin.security.unconfirmedEmailsTitle': 'Niepotwierdzone emaile',
    'admin.security.allEmailsConfirmed': 'Wszystkie emaile potwierdzone',
    'admin.security.confirmEmail': 'Potwierdź email',
    'admin.security.andMore': 'I {count} więcej...',

    // Admin Dashboard extras
    'admin.dashboard.userStats': 'Statystyki użytkowników',
    'admin.dashboard.viewAll': 'Zobacz wszystko',
    'admin.dashboard.activeUsers': 'Aktywni użytkownicy',
    'admin.dashboard.inactive': 'Nieaktywni',
    'admin.dashboard.activePercent': 'aktywnych',
    'admin.dashboard.assetPipeline': 'Pipeline przedmiotów',
    'admin.dashboard.draft': 'Szkic',
    'admin.dashboard.manageUsers': 'Zarządzaj użytkownikami',
    'admin.dashboard.viewEditUsers': 'Przeglądaj i edytuj',
    'admin.dashboard.verifyOrganizations': 'Weryfikuj organizacje',
    'admin.dashboard.allAssets': 'Wszystkie przedmioty',
    'admin.dashboard.browseAssets': 'Przeglądaj przedmioty',
    'admin.dashboard.viewSubscribers': 'Zobacz subskrybentów',

    // Admin Users
    'admin.users.title': 'Użytkownicy',
    'admin.users.subtitle': 'Zarządzaj użytkownikami systemu',
    'admin.users.search': 'Szukaj użytkowników...',
    'admin.users.allRoles': 'Wszystkie role',
    'admin.users.allStatuses': 'Wszystkie statusy',
    'admin.users.active': 'Aktywny',
    'admin.users.inactive': 'Nieaktywny',
    'admin.users.noUsers': 'Nie znaleziono użytkowników',
    'admin.users.role': 'Rola',
    'admin.users.status': 'Status',
    'admin.users.email': 'Email',
    'admin.users.organization': 'Organizacja',
    'admin.users.view': 'Zobacz',
    'admin.users.previous': 'Poprzednia',
    'admin.users.next': 'Następna',
    'admin.users.page': 'Strona',
    'admin.users.of': 'z',

    // Admin User Detail
    'admin.userDetail.title': 'Szczegóły użytkownika',
    'admin.userDetail.back': 'Powrót do użytkowników',
    'admin.userDetail.userInfo': 'Informacje o użytkowniku',
    'admin.userDetail.username': 'Nazwa użytkownika',
    'admin.userDetail.email': 'Email',
    'admin.userDetail.role': 'Rola',
    'admin.userDetail.organization': 'Organizacja',
    'admin.userDetail.createdAt': 'Data utworzenia',
    'admin.userDetail.status': 'Status',
    'admin.userDetail.emailStatus': 'Status emaila',
    'admin.userDetail.confirmed': 'Potwierdzony',
    'admin.userDetail.notConfirmed': 'Niepotwierdzony',
    'admin.userDetail.actions': 'Akcje',
    'admin.userDetail.activate': 'Aktywuj użytkownika',
    'admin.userDetail.deactivate': 'Dezaktywuj użytkownika',
    'admin.userDetail.confirmEmail': 'Potwierdź email',
    'admin.userDetail.userAssets': 'Przedmioty użytkownika',
    'admin.userDetail.noAssets': 'Brak przedmiotów dla tego użytkownika',
    'admin.userDetail.notFound': 'Nie znaleziono użytkownika',

    // Admin Organizations
    'admin.orgs.title': 'Organizacje',
    'admin.orgs.subtitle': 'Zarządzaj organizacjami',
    'admin.orgs.search': 'Szukaj organizacji...',
    'admin.orgs.allStatuses': 'Wszystkie statusy',
    'admin.orgs.verified': 'Zweryfikowane',
    'admin.orgs.unverified': 'Niezweryfikowane',
    'admin.orgs.noOrgs': 'Nie znaleziono organizacji',
    'admin.orgs.members': 'Członkowie',
    'admin.orgs.assets': 'Przedmioty',
    'admin.orgs.view': 'Zobacz',
    'admin.orgs.verify': 'Weryfikuj',
    'admin.orgs.unverify': 'Cofnij weryfikację',

    // Admin Organization Detail
    'admin.orgDetail.title': 'Szczegóły organizacji',
    'admin.orgDetail.back': 'Powrót do organizacji',
    'admin.orgDetail.info': 'Informacje o organizacji',
    'admin.orgDetail.name': 'Nazwa',
    'admin.orgDetail.description': 'Opis',
    'admin.orgDetail.walletAddress': 'Adres portfela',
    'admin.orgDetail.verified': 'Zweryfikowana',
    'admin.orgDetail.createdAt': 'Data utworzenia',
    'admin.orgDetail.yes': 'Tak',
    'admin.orgDetail.no': 'Nie',
    'admin.orgDetail.actions': 'Akcje',
    'admin.orgDetail.verify': 'Weryfikuj organizację',
    'admin.orgDetail.unverify': 'Cofnij weryfikację',
    'admin.orgDetail.members': 'Członkowie',
    'admin.orgDetail.noMembers': 'Brak członków',
    'admin.orgDetail.notFound': 'Nie znaleziono organizacji',

    // Admin Assets
    'admin.assets.title': 'Przedmioty',
    'admin.assets.subtitle': 'Przeglądaj wszystkie przedmioty w systemie',
    'admin.assets.search': 'Szukaj przedmiotów...',
    'admin.assets.allCategories': 'Wszystkie kategorie',
    'admin.assets.allStatuses': 'Wszystkie statusy',
    'admin.assets.minted': 'Zakotwiczone',
    'admin.assets.notMinted': 'Niezakotwiczone',
    'admin.assets.noAssets': 'Nie znaleziono przedmiotów',
    'admin.assets.owner': 'Właściciel',
    'admin.assets.category': 'Kategoria',
    'admin.assets.view': 'Zobacz',

    // Admin Newsletter
    'admin.newsletter.title': 'Subskrybenci newslettera',
    'admin.newsletter.subtitle': 'Zarządzaj subskrypcjami',
    'admin.newsletter.search': 'Szukaj po emailu...',
    'admin.newsletter.noSubscribers': 'Nie znaleziono subskrybentów',
    'admin.newsletter.subscribedAt': 'Data subskrypcji',
    'admin.newsletter.totalSubscribers': 'Łącznie subskrybentów',

    // App Layout
    'app.dashboard': 'Panel',
    'app.assets': 'Przedmioty',
    'app.reports': 'Raporty',
    'app.newAsset': 'Nowy przedmiot',
    'app.adminPanel': 'Panel Admina',
    'app.signOut': 'Wyloguj',
    'app.editAsset': 'Edytuj przedmiot',
    'app.settings': 'Ustawienia',
    'settings.title': 'Ustawienia',
    'settings.appearance': 'Wygląd',
    'settings.theme': 'Motyw',
    'settings.themeLight': 'Jasny',
    'settings.themeDark': 'Ciemny',
    'settings.language': 'Język',
    'settings.languageEn': 'English',
    'settings.languagePl': 'Polski',

    // Documents
    'documents.title': 'Dokumenty',
    'documents.upload': 'Dodaj dokument',
    'documents.empty': 'Brak dokumentów',
    'documents.saveFirst': 'Najpierw zapisz przedmiot, aby dodać dokumenty',
    'documents.blockchainNote': 'Dokumenty są uwzględnione w weryfikacji blockchain',
    'documents.delete': 'Usuń',
    'documents.download': 'Pobierz',
    'documents.view': 'Podgląd',
    'documents.uploading': 'Ładowanie...',
    'documents.hash': 'Hash',
    'documents.size': 'Rozmiar',

    // Common
    'common.loading': 'Ładowanie...',
    'common.saving': 'Zapisywanie...',
    'common.cancel': 'Anuluj',
    'common.save': 'Zapisz',
    'common.edit': 'Edytuj',
    'common.delete': 'Usuń',
    'common.confirmDelete': 'Czy na pewno chcesz usunąć ten przedmiot?',

    // Asset Form
    'asset.new': 'Nowy przedmiot',
    'asset.edit': 'Edytuj przedmiot',
    'asset.newSubtitle': 'Zarejestruj nowy produkt w rejestrze',
    'asset.editSubtitle': 'Zaktualizuj informacje o przedmiocie',
    'asset.type': 'Typ przedmiotu',
    'asset.typeSubtitle': 'Wybierz kategorię produktu',
    'asset.basicInfo': 'Podstawowe informacje',
    'asset.basicInfoSubtitle': 'Główne dane produktu',
    'asset.name': 'Nazwa',
    'asset.namePlaceholder': 'np. Rolex Submariner',
    'asset.brand': 'Marka',
    'asset.brandPlaceholder': 'np. Rolex',
    'asset.model': 'Model',
    'asset.modelPlaceholder': 'np. Submariner Date',
    'asset.serialNumber': 'Numer seryjny',
    'asset.serialNumberPlaceholder': 'np. SN-12345678',
    'asset.uniqueId': 'Unikalny ID',
    'asset.purchaseDetails': 'Szczegóły zakupu',
    'asset.purchaseDetailsSubtitle': 'Informacje o pochodzeniu i nabyciu',
    'asset.exactProductionDate': 'Dokładna data produkcji',
    'asset.productionDate': 'Data produkcji',
    'asset.year': 'Rok produkcji',
    'asset.yearPlaceholder': 'np. 2023',
    'asset.purchaseDate': 'Data zakupu',
    'asset.purchasePrice': 'Cena zakupu',
    'asset.currency': 'Waluta',
    'asset.description': 'Opis',
    'asset.descriptionPlaceholder': 'Dodatkowe informacje o produkcie...',
    'asset.descriptionHint': 'Uwzględnij stan, pochodzenie lub inne istotne szczegóły',
    'asset.blockchainRecord': 'Zapis w blockchain',
    'asset.blockchainRecordDesc': 'Po zapisaniu te informacje zostaną przygotowane do weryfikacji blockchain. Zapis staje się niezmienny po zakotwiczeniu.',
    'asset.saveChanges': 'Zapisz zmiany',
    'asset.createAsset': 'Utwórz przedmiot',

    // Asset Types / Categories
    'category.vehicle': 'Pojazd',
    'category.watch': 'Zegarek',
    'category.electronics': 'Elektronika',
    'category.art': 'Sztuka',
    'category.instrument': 'Instrument',
    'category.other': 'Inne',

    // Assets List
    'assets.title': 'Przedmioty',
    'assets.subtitle': 'Zarządzaj zarejestrowanymi produktami',
    'assets.addAsset': 'Dodaj przedmiot',
    'assets.searchPlaceholder': 'Szukaj po nazwie, numerze seryjnym...',
    'assets.allTypes': 'Wszystkie typy',
    'assets.allStatus': 'Wszystkie statusy',
    'assets.tableProduct': 'Produkt',
    'assets.tableType': 'Typ',
    'assets.tableStatus': 'Status',
    'assets.tableSerial': 'Nr seryjny',
    'assets.tableActions': 'Akcje',
    'assets.noAssetsYet': 'Brak zarejestrowanych przedmiotów',
    'assets.noAssetsMatch': 'Brak przedmiotów spełniających kryteria',
    'assets.addFirstAsset': 'Dodaj pierwszy przedmiot →',
    'assets.showing': 'Wyświetlanie',
    'assets.of': 'z',
    'assets.assets': 'przedmiotów',

    // Status Labels
    'status.draft': 'Szkic',
    'status.verified': 'Zweryfikowany',
    'status.minted': 'Zakotwiczony',

    // Asset Types
    'assetType.VEHICLE': 'Pojazd',
    'assetType.WATCH': 'Zegarek',
    'assetType.ELECTRONICS': 'Elektronika',
    'assetType.ART': 'Sztuka',
    'assetType.INSTRUMENT': 'Instrument',
    'assetType.OTHER': 'Inne',

    // Dashboard
    'dashboard.title': 'Panel',
    'dashboard.subtitle': 'Przegląd rejestru produktów',
    'dashboard.totalAssets': 'Wszystkie przedmioty',
    'dashboard.allRegisteredItems': 'Wszystkie zarejestrowane przedmioty',
    'dashboard.draft': 'Szkice',
    'dashboard.awaitingCompletion': 'Do uzupełnienia',
    'dashboard.verified': 'Zweryfikowane',
    'dashboard.readyToMint': 'Gotowe do zakotwiczenia',
    'dashboard.minted': 'Zakotwiczone',
    'dashboard.onBlockchain': 'W blockchain',
    'dashboard.assetsByType': 'Przedmioty według typu',
    'dashboard.types': 'typów',
    'dashboard.noAssetsYet': 'Brak przedmiotów',
    'dashboard.addFirstAsset': 'Dodaj pierwszy przedmiot →',
    'dashboard.recentAssets': 'Ostatnie przedmioty',
    'dashboard.viewAll': 'Zobacz wszystkie →',
    'dashboard.noRecentActivity': 'Brak ostatniej aktywności',
    'dashboard.assetPipeline': 'Pipeline przedmiotów',

    // Reports
    'reports.title': 'Raporty',
    'reports.subtitle': 'Analityka i podsumowania przedmiotów',
    'reports.comingSoon': 'Wkrótce',
    'reports.moduleInDevelopment': 'Moduł raportów w przygotowaniu',
    'reports.moduleDescription': 'Pracujemy nad zaawansowanymi raportami i wizualizacjami. Będziesz mógł generować podsumowania wartości przedmiotów, kosztów utrzymania, analizy amortyzacji i więcej.',
    'reports.plannedFeatures': 'Planowane funkcje',
    'reports.plannedFeaturesSubtitle': 'Co pojawi się w module raportów',
    'reports.featuresPlanned': 'funkcji zaplanowanych',
    'reports.feature': 'Funkcja',
    'reports.planned': 'Planowana',
    'reports.haveSuggestions': 'Masz sugestie?',
    'reports.feedbackDescription': 'Budujemy to dla Ciebie. Daj nam znać, jakie raporty i analizy byłyby dla Ciebie najbardziej wartościowe.',
    'reports.sendFeedback': 'Wyślij opinię',
    'reports.valueReport': 'Raport wartości',
    'reports.valueReportDesc': 'Zestawienie wartości przedmiotów według kategorii',
    'reports.depreciation': 'Amortyzacja',
    'reports.depreciationDesc': 'Analiza utraty wartości w czasie',
    'reports.serviceCosts': 'Koszty serwisowe',
    'reports.serviceCostsDesc': 'Zestawienie kosztów utrzymania i napraw',
    'reports.assignments': 'Przypisania',
    'reports.assignmentsDesc': 'Przedmioty przypisane do członków zespołu',
    'reports.dataExport': 'Eksport danych',
    'reports.dataExportDesc': 'Eksport do PDF, Excel i CSV',
    'reports.serviceSchedule': 'Harmonogram serwisowy',
    'reports.serviceScheduleDesc': 'Kalendarz planowanych przeglądów i serwisów',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem('language') as Language;
      if (stored === 'en' || stored === 'pl') return stored;
    }
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
